name: Merge Upstream

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering as well

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream changes
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/anmolg-ebbo/GSA-Acquisition-FAR/merge-upstream \
            -d '{"branch":"master"}'
